name: Auto Deploy to Fly.io

on:
  workflow_run:
    workflows:
      - "Auto Update Tailscale"
    types:
      - "completed"
  workflow_dispatch:

jobs:
  Tailscale:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Cleanup
        run: |
          python -m pip install -r requirements.txt
          python cleanup.py
        env:
          TS_API_DOMAIN: ${{ secrets.TS_API_DOMAIN }}
          TS_TAG: ${{ secrets.TS_TAG }}
          TS_API_TOKEN: ${{ secrets.TS_API_TOKEN }}
  Fly:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: Tailscale
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}